# Generated by Django 5.2 on 2025-04-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0006_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_at']},
        ),
    ]
